blueprint:
  name: Remotec ZRC-90
  description: Create automations for the 'Remotec ZRC-90' using the OZW integration.
  domain: automation
  input:
    remotec_pad:
      name: ZRC-90 8 Keypad
      description: "List of available Remotec ZRC-90 remotes to configure. This list is only a reference."
      selector:
        device:
          integration: zwave_js
          manufacturer: Remotec
          model: BW8510
    ozw_node_id:
      name: Node ID
      description: "Enter the node id. For now, this field is required. "
    button_1:
      name: Single Press Button 1
      description: Action to run on button press.
      default: []
      selector:
        action: {}
    button_1_1:
      name: Double Press Button 1
      description: Action to run on a double button press.
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
variables:
  device_id: !input remotec_pad
  ozw_node_id: !input ozw_node_id
trigger:
  - platform: event
    event_type: zwave.scene_activate
    event_data:
      scene_value_id: 1
condition: "{{ trigger.event.data.node_id == (ozw_node_id | int) }}"
action:
  - variables:
      scene_id: "{{ trigger.event.data.scene_id }}"
      scene_data: "{{ trigger.event.data.scene_value_id }}"
  - choose:
      - conditions: "{{ scene_id == 1 and scene_data == 1}}"
        sequence: !input button_1
      - conditions: "{{ scene_id == 1 and scene_data == 3 }}"
        sequence: !input button_1_1
