blueprint:
  name: Remotec ZRC-90
  description: Create automations for the 'Remotec ZRC-90' using the OZW integration.
  domain: automation
  input:
    remotec_pad:
      name: ZRC-90 8 Keypad
      description: "List of available Remotec ZRC-90 remotes to configure. This list is only a reference."
      selector:
        device:
          integration: zwave_js
    ozw_node_id:
      name: Node ID
      description: "Enter the node id. For now, this field is required."
    button_1:
      name: Single Press Button 1
      description: Action to run on button press.
      default: []
      selector:
        action: {}
    button_1_1:
      name: Double Press Button 1
      description: Action to run on a double button press.
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
variables:
  device_id: !input remotec_pad
  ozw_node_id: !input ozw_node_id
trigger:
  - platform: event
    event_type: zwave_js_event.value_notification
condition: "{{ trigger.value_notification.node_id == (ozw_node_id | int) }}"
action:
  - variables:
      scene_id: "{{ trigger.value_notification.property_key }}"
      scene_data: "{{ trigger.value_notification.value_raw }}"
  - choose:
      - conditions: "{{ scene_id == 001 and scene_data == 0 }}"
        sequence: !input button_1
      - conditions: "{{ scene_id == 001 and scene_data == 3 }}"
        sequence: !input button_1_1
# Single Key Pres Button 1
# {
#    "event_type": "zwave_js_event",
#    "data": {
#        "type": "value_notification",
#        "domain": "zwave_js",
#        "node_id": 9,
#        "home_id": 3913730099,
#        "endpoint": 0,
#        "device_id": "968bbd50de1012587d008fcc35e80c27",
#        "command_class": 91,
#        "command_class_name": "Central Scene",
#        "label": "Scene 001",
#        "property": "scene",
#        "property_name": "scene",
#        "property_key": "001",
#        "property_key_name": "001",
#        "value": "KeyPressed",
#        "value_raw": 0
#    },

#Double Key Press Button 1
# {
#    "event_type": "zwave_js_event",
#    "data": {
#        "type": "value_notification",
#        "domain": "zwave_js",
#        "node_id": 9,
#        "home_id": 3913730099,
#        "endpoint": 0,
#        "device_id": "968bbd50de1012587d008fcc35e80c27",
#        "command_class": 91,
#        "command_class_name": "Central Scene",
#        "label": "Scene 001",
#        "property": "scene",
#        "property_name": "scene",
#        "property_key": "001",
#        "property_key_name": "001",
#        "value": "KeyPressed2x",
#        "value_raw": 3
#    },
